# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2UzpoQVS0pZFJfNnfO22d8qxTcIvfdj
"""

# ============================================================
# PROYECTO INTERACTIVO DE SUSTENTABILIDAD
# Google Colab - versión completa e interactiva
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
import io
import math

plt.style.use("ggplot")

# ============================================================
# 1. SUBIR ARCHIVO
# ============================================================

def subir_excel():
    print("=" * 70)
    print("SUBE TU ARCHIVO EXCEL (.xlsx)")
    print("=" * 70)
    archivos = files.upload()
    nombre = list(archivos.keys())[0]
    excel_bytes = io.BytesIO(archivos[nombre])
    print(f"\nArchivo cargado correctamente: {nombre}\n")
    return excel_bytes, nombre


# ============================================================
# 2. CARGAR TODAS LAS HOJAS
# ============================================================

def cargar_libro(excel_bytes):
    xls = pd.ExcelFile(excel_bytes)
    hojas = xls.sheet_names
    libro = {}
    for hoja in hojas:
        libro[hoja] = pd.read_excel(xls, sheet_name=hoja)
    return libro


# ============================================================
# 3. LIMPIEZA GENERAL
# ============================================================

def normalizar_nombre_columna(col):
    if pd.isna(col):
        return "columna_vacia"
    return str(col).strip()

def limpiar_dataframe(df):
    df = df.copy()
    df.columns = [normalizar_nombre_columna(c) for c in df.columns]
    df = df.dropna(how="all")
    df = df.dropna(axis=1, how="all")
    df = df.reset_index(drop=True)
    return df

def obtener_hojas_utiles(libro):
    return [h for h in libro.keys() if h.lower() not in ["portada"]]

def es_hoja_medidas(nombre_hoja):
    return nombre_hoja.strip().lower() == "medidas"

def convertir_si_numero(serie):
    return pd.to_numeric(serie, errors="coerce")

def detectar_tabla_analizable(df):
    """
    Intenta detectar la fila donde empiezan encabezados útiles.
    En tus hojas suele ser la fila 1.
    """
    df = limpiar_dataframe(df)

    if len(df) < 2:
        return None

    # Intento 1: usar la segunda fila como encabezado real
    posible = df.copy()
    encabezados = [str(x).strip() for x in posible.iloc[0].tolist()]
    # si la primera fila es muy vacía, usamos la segunda
    if sum(pd.isna(posible.iloc[0])) > sum(pd.isna(posible.iloc[1])) and len(posible) > 1:
        encabezados = [str(x).strip() for x in posible.iloc[1].tolist()]
        posible = posible.iloc[2:].copy()
    else:
        posible = posible.iloc[1:].copy()

    posible.columns = encabezados
    posible = posible.dropna(how="all")
    posible = posible.reset_index(drop=True)

    return posible

def preparar_hoja(nombre_hoja, df):
    """
    Devuelve un DataFrame limpio y útil para análisis.
    """
    if es_hoja_medidas(nombre_hoja):
        return limpiar_dataframe(df)

    tabla = detectar_tabla_analizable(df)
    if tabla is None or tabla.empty:
        return None

    # quitar fila TOTAL si existe, pero guardarla opcionalmente
    tabla = tabla.copy()

    # Normalizar primera columna
    primera_col = tabla.columns[0]
    tabla[primera_col] = tabla[primera_col].astype(str).str.strip()

    # eliminar filas vacías
    tabla = tabla[tabla[primera_col].str.lower() != "nan"]

    return tabla.reset_index(drop=True)


# ============================================================
# 4. DETECTAR TIPO DE HOJA
# ============================================================

def detectar_tipo_hoja(tabla):
    """
    Determina si la hoja es numérica o categórica.
    """
    if tabla is None or tabla.empty:
        return "desconocida"

    primera_col = tabla.columns[0]
    muestra = pd.to_numeric(tabla[primera_col], errors="coerce")

    # Si la mayoría de la primera columna es numérica, es hoja numérica
    proporcion_numerica = muestra.notna().mean()
    if proporcion_numerica >= 0.6:
        return "numerica"
    return "categorica"


def obtener_columnas_principales(tabla):
    """
    Busca columnas esperadas:
    x/respuesta, frecuencia, frecuencia relativa, acumuladas
    """
    columnas = list(tabla.columns)

    col_base = columnas[0]
    col_frecuencia = None
    col_relativa = None
    col_acum_menor = None
    col_acum_mayor = None

    for c in columnas:
        texto = str(c).lower()
        if "frecuencia" in texto and "relativa" not in texto and "acum" not in texto:
            col_frecuencia = c
        elif "frecuencia relativa" in texto:
            col_relativa = c
        elif "acum" in texto and "menor" in texto:
            col_acum_menor = c
        elif "acum" in texto and "mayor" in texto:
            col_acum_mayor = c

    return {
        "base": col_base,
        "frecuencia": col_frecuencia,
        "relativa": col_relativa,
        "acum_menor": col_acum_menor,
        "acum_mayor": col_acum_mayor
    }


# ============================================================
# 5. FUNCIONES DE VISUALIZACIÓN
# ============================================================

def mostrar_datos(tabla, max_filas=20):
    print("\nVista previa de datos:")
    print(tabla.head(max_filas).to_string(index=False))

def mostrar_resumen_hoja(nombre_hoja, tabla):
    print("\n" + "=" * 70)
    print(f"RESUMEN DE LA HOJA: {nombre_hoja}")
    print("=" * 70)
    print(f"Filas: {tabla.shape[0]}")
    print(f"Columnas: {tabla.shape[1]}")
    print("Nombres de columnas:")
    for c in tabla.columns:
        print(f"- {c}")

def grafica_barras(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    x = tabla[cols["base"]]
    y = convertir_si_numero(tabla[cols["frecuencia"]])

    plt.figure(figsize=(10, 5))
    plt.bar(x, y, color="firebrick")
    plt.title(f"Barras - {titulo}")
    plt.xlabel("Categoría / Valor")
    plt.ylabel("Frecuencia")
    plt.xticks(rotation=30, ha="right")
    plt.tight_layout()
    plt.show()

def grafica_barras_h(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    x = tabla[cols["base"]]
    y = convertir_si_numero(tabla[cols["frecuencia"]])

    plt.figure(figsize=(10, 5))
    plt.barh(x, y, color="teal")
    plt.title(f"Barras horizontales - {titulo}")
    plt.xlabel("Frecuencia")
    plt.ylabel("Categoría / Valor")
    plt.tight_layout()
    plt.show()

def grafica_pastel(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    etiquetas = tabla[cols["base"]].astype(str)
    valores = convertir_si_numero(tabla[cols["frecuencia"]])

    plt.figure(figsize=(8, 8))
    plt.pie(valores, labels=etiquetas, autopct="%1.1f%%", startangle=90)
    plt.title(f"Gráfica de pastel - {titulo}")
    plt.tight_layout()
    plt.show()

def grafica_dona(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    etiquetas = tabla[cols["base"]].astype(str)
    valores = convertir_si_numero(tabla[cols["frecuencia"]])

    plt.figure(figsize=(8, 8))
    wedges, texts, autotexts = plt.pie(valores, labels=etiquetas, autopct="%1.1f%%", startangle=90)
    centro = plt.Circle((0, 0), 0.55, fc="white")
    fig = plt.gcf()
    fig.gca().add_artist(centro)
    plt.title(f"Gráfica de dona - {titulo}")
    plt.tight_layout()
    plt.show()

def grafica_linea(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    x = tabla[cols["base"]]
    y = convertir_si_numero(tabla[cols["frecuencia"]])

    plt.figure(figsize=(10, 5))
    plt.plot(x, y, marker="o", linewidth=2, color="navy")
    plt.title(f"Gráfica de línea - {titulo}")
    plt.xlabel("Categoría / Valor")
    plt.ylabel("Frecuencia")
    plt.xticks(rotation=30, ha="right")
    plt.tight_layout()
    plt.show()

def grafica_area(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    x_labels = tabla[cols["base"]].astype(str).tolist()
    y = convertir_si_numero(tabla[cols["frecuencia"]]).tolist()
    x = range(len(x_labels))

    plt.figure(figsize=(10, 5))
    plt.fill_between(x, y, color="orange", alpha=0.5)
    plt.plot(x, y, color="darkorange", marker="o")
    plt.title(f"Gráfica de área - {titulo}")
    plt.xlabel("Categoría / Valor")
    plt.ylabel("Frecuencia")
    plt.xticks(list(x), x_labels, rotation=30, ha="right")
    plt.tight_layout()
    plt.show()

def grafica_histograma(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    valores = convertir_si_numero(tabla[cols["base"]])
    frecuencias = convertir_si_numero(tabla[cols["frecuencia"]])

    datos = []
    for valor, frec in zip(valores, frecuencias):
        if pd.notna(valor) and pd.notna(frec):
            datos.extend([valor] * int(frec))

    if not datos:
        print("No hay datos suficientes para histograma.")
        return

    plt.figure(figsize=(10, 5))
    plt.hist(datos, bins=min(10, len(set(datos))), color="steelblue", edgecolor="black")
    plt.title(f"Histograma - {titulo}")
    plt.xlabel("Valor")
    plt.ylabel("Frecuencia")
    plt.tight_layout()
    plt.show()

def grafica_poligono_frecuencias(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    x = convertir_si_numero(tabla[cols["base"]])
    y = convertir_si_numero(tabla[cols["frecuencia"]])

    plt.figure(figsize=(10, 5))
    plt.plot(x, y, marker="o", linewidth=2, color="purple")
    plt.title(f"Polígono de frecuencias - {titulo}")
    plt.xlabel("Valor")
    plt.ylabel("Frecuencia")
    plt.tight_layout()
    plt.show()

def grafica_ojiva_menor(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    if cols["acum_menor"] is None:
        print("Esta hoja no tiene columna de acumulada menor.")
        return

    x = convertir_si_numero(tabla[cols["base"]])
    y = convertir_si_numero(tabla[cols["acum_menor"]])

    plt.figure(figsize=(10, 5))
    plt.plot(x, y, marker="o", linewidth=2, color="green")
    plt.title(f"Ojiva menor - {titulo}")
    plt.xlabel("Valor")
    plt.ylabel("Frecuencia acumulada menor")
    plt.tight_layout()
    plt.show()

def grafica_ojiva_mayor(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    if cols["acum_mayor"] is None:
        print("Esta hoja no tiene columna de acumulada mayor.")
        return

    x = convertir_si_numero(tabla[cols["base"]])
    y = convertir_si_numero(tabla[cols["acum_mayor"]])

    plt.figure(figsize=(10, 5))
    plt.plot(x, y, marker="o", linewidth=2, color="red")
    plt.title(f"Ojiva mayor - {titulo}")
    plt.xlabel("Valor")
    plt.ylabel("Frecuencia acumulada mayor")
    plt.tight_layout()
    plt.show()

def grafica_ojiva_combinada(tabla, titulo):
    cols = obtener_columnas_principales(tabla)
    if cols["acum_menor"] is None or cols["acum_mayor"] is None:
        print("Esta hoja no tiene ambas acumuladas para la ojiva combinada.")
        return

    x = convertir_si_numero(tabla[cols["base"]])
    y1 = convertir_si_numero(tabla[cols["acum_menor"]])
    y2 = convertir_si_numero(tabla[cols["acum_mayor"]])

    plt.figure(figsize=(10, 5))
    plt.plot(x, y1, marker="o", linewidth=2, color="green", label="Ojiva menor")
    plt.plot(x, y2, marker="s", linewidth=2, color="red", label="Ojiva mayor")
    plt.title(f"Ojiva combinada - {titulo}")
    plt.xlabel("Valor")
    plt.ylabel("Frecuencia acumulada")
    plt.legend()
    plt.tight_layout()
    plt.show()


# ============================================================
# 6. MOSTRAR TODAS LAS GRÁFICAS DE UNA HOJA
# ============================================================

def generar_todas_las_graficas(nombre_hoja, tabla):
    tipo = detectar_tipo_hoja(tabla)

    print("\n" + "=" * 70)
    print(f"GENERANDO TODAS LAS GRÁFICAS DE: {nombre_hoja}")
    print("=" * 70)

    try:
        grafica_barras(tabla, nombre_hoja)
    except:
        print("No se pudo generar barras.")

    try:
        grafica_barras_h(tabla, nombre_hoja)
    except:
        print("No se pudo generar barras horizontales.")

    try:
        grafica_pastel(tabla, nombre_hoja)
    except:
        print("No se pudo generar pastel.")

    try:
        grafica_dona(tabla, nombre_hoja)
    except:
        print("No se pudo generar dona.")

    try:
        grafica_linea(tabla, nombre_hoja)
    except:
        print("No se pudo generar línea.")

    try:
        grafica_area(tabla, nombre_hoja)
    except:
        print("No se pudo generar área.")

    if tipo == "numerica":
        try:
            grafica_histograma(tabla, nombre_hoja)
        except:
            print("No se pudo generar histograma.")

        try:
            grafica_poligono_frecuencias(tabla, nombre_hoja)
        except:
            print("No se pudo generar polígono de frecuencias.")

        try:
            grafica_ojiva_menor(tabla, nombre_hoja)
        except:
            print("No se pudo generar ojiva menor.")

        try:
            grafica_ojiva_mayor(tabla, nombre_hoja)
        except:
            print("No se pudo generar ojiva mayor.")

        try:
            grafica_ojiva_combinada(tabla, nombre_hoja)
        except:
            print("No se pudo generar ojiva combinada.")


# ============================================================
# 7. RESUMEN DEL PROYECTO
# ============================================================

def mostrar_hoja_medidas(tabla):
    print("\n" + "=" * 70)
    print("MEDIDAS DE TENDENCIA CENTRAL Y DISPERSIÓN")
    print("=" * 70)
    print(tabla.to_string(index=False))

def generar_todo_el_proyecto(datos_preparados):
    print("\n" + "=" * 70)
    print("GENERANDO TODO EL PROYECTO")
    print("=" * 70)

    for nombre_hoja, tabla in datos_preparados.items():
        if tabla is None:
            continue

        if es_hoja_medidas(nombre_hoja):
            mostrar_hoja_medidas(tabla)
        else:
            mostrar_resumen_hoja(nombre_hoja, tabla)
            mostrar_datos(tabla, max_filas=10)
            generar_todas_las_graficas(nombre_hoja, tabla)


# ============================================================
# 8. MENÚ INTERACTIVO
# ============================================================

def mostrar_menu_principal():
    print("\n" + "=" * 70)
    print("MENÚ PRINCIPAL DEL PROYECTO")
    print("=" * 70)
    print("1. Ver hojas disponibles")
    print("2. Ver datos de una hoja")
    print("3. Ver resumen de una hoja")
    print("4. Generar una gráfica específica")
    print("5. Generar todas las gráficas de una hoja")
    print("6. Ver hoja de medidas")
    print("7. Generar todo el proyecto completo")
    print("8. Salir")

def elegir_hoja(datos_preparados):
    hojas = list(datos_preparados.keys())
    print("\nHojas disponibles:")
    for i, h in enumerate(hojas, start=1):
        print(f"{i}. {h}")

    try:
        opcion = int(input("\nElige el número de la hoja: "))
        if 1 <= opcion <= len(hojas):
            return hojas[opcion - 1]
    except:
        pass

    print("Selección inválida.")
    return None

def mostrar_menu_graficas():
    print("\nTipos de gráficas:")
    print("1. Barras")
    print("2. Barras horizontales")
    print("3. Pastel")
    print("4. Dona")
    print("5. Línea")
    print("6. Área")
    print("7. Histograma")
    print("8. Polígono de frecuencias")
    print("9. Ojiva menor")
    print("10. Ojiva mayor")
    print("11. Ojiva combinada")

def ejecutar_grafica_especifica(nombre_hoja, tabla):
    tipo = detectar_tipo_hoja(tabla)
    mostrar_menu_graficas()

    try:
        opcion = int(input("\n¿Qué gráfica quieres ver? "))
    except:
        print("Opción inválida.")
        return

    if opcion == 1:
        grafica_barras(tabla, nombre_hoja)
    elif opcion == 2:
        grafica_barras_h(tabla, nombre_hoja)
    elif opcion == 3:
        grafica_pastel(tabla, nombre_hoja)
    elif opcion == 4:
        grafica_dona(tabla, nombre_hoja)
    elif opcion == 5:
        grafica_linea(tabla, nombre_hoja)
    elif opcion == 6:
        grafica_area(tabla, nombre_hoja)
    elif opcion == 7:
        if tipo == "numerica":
            grafica_histograma(tabla, nombre_hoja)
        else:
            print("El histograma solo aplica mejor para hojas numéricas.")
    elif opcion == 8:
        if tipo == "numerica":
            grafica_poligono_frecuencias(tabla, nombre_hoja)
        else:
            print("El polígono de frecuencias solo aplica mejor para hojas numéricas.")
    elif opcion == 9:
        if tipo == "numerica":
            grafica_ojiva_menor(tabla, nombre_hoja)
        else:
            print("La ojiva menor solo aplica mejor para hojas numéricas.")
    elif opcion == 10:
        if tipo == "numerica":
            grafica_ojiva_mayor(tabla, nombre_hoja)
        else:
            print("La ojiva mayor solo aplica mejor para hojas numéricas.")
    elif opcion == 11:
        if tipo == "numerica":
            grafica_ojiva_combinada(tabla, nombre_hoja)
        else:
            print("La ojiva combinada solo aplica mejor para hojas numéricas.")
    else:
        print("Opción inválida.")


# ============================================================
# 9. MAIN
# ============================================================

def main():
    excel_bytes, nombre_archivo = subir_excel()
    libro = cargar_libro(excel_bytes)

    hojas_utiles = obtener_hojas_utiles(libro)
    datos_preparados = {}

    for hoja in hojas_utiles:
        datos_preparados[hoja] = preparar_hoja(hoja, libro[hoja])

    print("=" * 70)
    print("PROYECTO LISTO")
    print("=" * 70)
    print(f"Archivo analizado: {nombre_archivo}")

    while True:
        mostrar_menu_principal()
        opcion = input("\nElige una opción: ").strip()

        if opcion == "1":
            print("\nHojas disponibles:")
            for h in datos_preparados.keys():
                print("-", h)

        elif opcion == "2":
            hoja = elegir_hoja(datos_preparados)
            if hoja:
                tabla = datos_preparados[hoja]
                if tabla is not None:
                    mostrar_datos(tabla)
                else:
                    print("No se pudo preparar esa hoja.")

        elif opcion == "3":
            hoja = elegir_hoja(datos_preparados)
            if hoja:
                tabla = datos_preparados[hoja]
                if tabla is not None:
                    mostrar_resumen_hoja(hoja, tabla)
                else:
                    print("No se pudo preparar esa hoja.")

        elif opcion == "4":
            hoja = elegir_hoja(datos_preparados)
            if hoja:
                tabla = datos_preparados[hoja]
                if tabla is not None and not es_hoja_medidas(hoja):
                    ejecutar_grafica_especifica(hoja, tabla)
                else:
                    print("La hoja de medidas no usa este menú de gráficas.")

        elif opcion == "5":
            hoja = elegir_hoja(datos_preparados)
            if hoja:
                tabla = datos_preparados[hoja]
                if tabla is not None and not es_hoja_medidas(hoja):
                    generar_todas_las_graficas(hoja, tabla)
                else:
                    print("La hoja de medidas no usa este menú de gráficas.")

        elif opcion == "6":
            if "Medidas" in datos_preparados:
                mostrar_hoja_medidas(datos_preparados["Medidas"])
            else:
                print("No se encontró la hoja 'Medidas'.")

        elif opcion == "7":
            generar_todo_el_proyecto(datos_preparados)

        elif opcion == "8":
            print("\nPrograma finalizado. ¡Proyecto terminado!")
            break

        else:
            print("Opción inválida. Inténtalo otra vez.")


# Ejecutar
main()